
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js"></script>
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$scriptString = '
    var BASE_URL = \'' . /* @noEscape */ $block->getUrl('*') . '\';
    var FORM_KEY = \'' . /* @noEscape */ $block->getFormKey() . '\';
    var require = {
        \'baseUrl\': \'' . /* @noEscape */ $block->getViewFileUrl('/') . '\'
    };';

echo /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false);
