<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Hyva\Admin\ViewModel\HyvaGrid\GridFilterInterface $filter */

$escaper = $escaper ?? $block;

$value = $filter->getValue();

?>
<select name="<?= $escaper->escapeHtmlAttr($filter->getInputName()) ?>"
        form="<?= $escaper->escapeHtmlAttr($filter->getFormId()) ?>"
        class="form-select w-full"
        @change="formGridUpdate"
>
    <option value=""> </option>
    <option value="1"<?= isset($value) && $value ? ' selected' : '' ?>><?= $escaper->escapeHtml(__('Yes')) ?></option>
    <option value="0"<?= isset($value) && !$value && $value !== '' ? ' selected' : '' ?>><?= $escaper->escapeHtml(__('No')) ?></option>
</select>
