<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Hyva\Admin\ViewModel\HyvaGrid\GridFilterInterface $filter */

$escaper = $escaper ?? $block;

?>
<div class="flex flex-row flex-no-wrap gap-x-2 items-center text-left">
    <span class="w-1/2 flex">
        <?= $escaper->escapeHtml(__('From:')) ?>
    </span>
    <span class="w-1/2 max-w-full" style="min-width: 150px;">
        <input type="date" form="<?= $filter->getFormId() ?>" class="form-input"
               name="<?= $escaper->escapeHtmlAttr($filter->getInputName('from')) ?>"
               value="<?= $escaper->escapeHtmlAttr($filter->getValue('from')) ?>"
        />
    </span>
</div>
<div class="flex flex-row flex-no-wrap gap-x-2 items-center text-left">
    <span class="w-1/2">
    <?= $escaper->escapeHtml(__('To:')) ?>
    </span>
    <span class="w-1/2 max-w-full" style="min-width: 150px;">
        <input type="date" form="<?= $filter->getFormId() ?>" class="form-input"
               name="<?= $escaper->escapeHtmlAttr($filter->getInputName('to')) ?>"
               value="<?= $escaper->escapeHtmlAttr($filter->getValue('to')) ?>"
        />
    </span>
</div>
