<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Hyva\Admin\ViewModel\HyvaGrid\GridFilterInterface $filter */

$escaper = $escaper ?? $block;

?>
<input type="text" form="<?= $filter->getFormId() ?>" class=""
       name="<?= $escaper->escapeHtmlAttr($filter->getInputName()) ?>"
       value="<?= $escaper->escapeHtmlAttr($filter->getValue()) ?>"
/>
