<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Hyva\Admin\ViewModel\HyvaForm\FormGroupInterface $group */

$escaper = $escaper ?? $block;

?>
<?php foreach ($group->getFields() as $field): ?>
<div class="flex flex-col md:flex-row">
    <div class="w-40 min-w-full max-width-none">
        <label for="<?= $escaper->escapeHtmlAttr($field->getName()) ?>">
            <?= $escaper->escapeHtml($field->getLabel()) ?>:
        </label>
    </div>
    <div class="border border-gray-200">
        <?= $field->getHtml() ?>
    </div>
</div>
<?php endforeach; ?>
