<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Hyva\Admin\ViewModel\HyvaGrid\GridFilterInterface $filter */

?>
<div>
<?= __('From:') ?>
    <input type="text" form="<?= $filter->getFormId() ?>" class=""
           name="<?= $escaper->escapeHtmlAttr($filter->getInputName('from')) ?>"
           value="<?= $escaper->escapeHtmlAttr($filter->getValue('from')) ?>"/>
</div>
<div>
<?= __('To:') ?>
    <input type="text" form="<?= $filter->getFormId() ?>" class=""
           name="<?= $escaper->escapeHtmlAttr($filter->getInputName('to')) ?>"
           value="<?= $escaper->escapeHtmlAttr($filter->getValue('to')) ?>"/>
</div>
