<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Hyva\Admin\ViewModel\HyvaGrid\GridFilterInterface $filter */

?>
<?= __('From:') ?> <input type="text" form="<?= $filter->getFormId() ?>" class="shadow"
                          name="<?= $escaper->escapeHtmlAttr($filter->getInputName('from')) ?>"
                          value="<?= $escaper->escapeHtmlAttr($filter->getValue('from')) ?>"/>
<?= __('To:') ?> <input type="text" form="<?= $filter->getFormId() ?>" class="shadow"
                        name="<?= $escaper->escapeHtmlAttr($filter->getInputName('to')) ?>"
                        value="<?= $escaper->escapeHtmlAttr($filter->getValue('to')) ?>"/>
