<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Hyva\Admin\ViewModel\HyvaForm\FormFieldDefinitionInterface $field */

$escaper = $escaper ?? $block;

?>
<fieldset>
<?php foreach ($field->getOptions() as $i => $option): ?>
    <?php $id = $escaper->escapeHtmlAttr($field->getName() . $i); ?>

<input type="radio" name="<?= $escaper->escapeHtmlAttr($field->getName())?>" id="<?= $id ?>"
       value="<?= $escaper->escapeHtmlAttr($option['value'])?>"
       <?= $field->getValue() === $option['value'] ? 'checked' : '' ?>
       <?= $field->isDisabled() ? 'disabled' : '' ?> />
<label for="<?= $id ?>"><?= $escaper->escapeHtml($option['label']) ?></label>
<?php endforeach; ?>
</fieldset>
