<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Hyva\Admin\ViewModel\HyvaForm\FormFieldDefinitionInterface $field */

$escaper = $escaper ?? $block;

?>
<input form="<?= $field->getFormName() ?>" id="<?= $escaper->escapeHtmlAttr($field->getName()) ?>" type="text"
       value="<?= $escaper->escapeHtmlAttr($field->getValue()) ?>"/>
