<?php
declare(strict_types=1);

use Magento\Backend\Block\Template;
use Magento\Framework\Escaper;

// phpcs:ignore Generic.Files.LineLength.TooLong

/** @var Escaper $escaper */
/** @var Template $block */
?>
<script>
    function initDataTable<?= /** @noEscape */ $uniqueId ?>() {

        const closest = function (selector, element, top)
        {
            if (! element || element === (top || document)) {
                return null;
            }
            return element.matches(selector)
                ? element
                : closest(selector, element.parentElement, top);
        }

        return {
            refs: false,
            loading: false,
            selectedRows: [],
            hiddenCols: [
                <?php foreach ($grid->getColumnDefinitions() as $column): ?>
                <?php if ($column->isInitiallyHidden()): ?>
                'col-<?= $escaper->escapeHtml($column->getKey()) ?>',
                <?php endif; ?>
                <?php endforeach; ?>
            ],
            massActionStorageName: '<?= $escaper->escapeHtml($grid->getGridName()) . '-selectedRows' ?>',
            hiddenColsStorageName: '<?= $escaper->escapeHtml($grid->getGridName()) . '-hiddenCols' ?>',

            columns: [
                <?php foreach ($grid->getColumnDefinitions() as $column): ?>
                {
                    'key': 'col-<?= $escaper->escapeJs($column->getKey()) ?>',
                    'value': '<?= $escaper->escapeHtml(__($column->getLabel())) ?>'
                },
                <?php endforeach; ?>
            ],

            open: false,
            openExport: false,
            filterUri: window.location.href,

            initState() {
                this.$watch('selectedRows', this.storeSelectedRows.bind(this));
                this.selectedRows = this.getSelectedRows();
                this.hiddenCols = this.getHiddenCols();
                <?php if ($navigation->hasFilters()): ?>
                this.filterUri = this.getFormUriEncoded(document.getElementById('<?= $navigation->getFilterFormId() ?>'));
                <?php endif; ?>
            },

            getSelectedRows() {
                const selectedRowsJson = window.sessionStorage.getItem(this.massActionStorageName);
                return selectedRowsJson ? JSON.parse(selectedRowsJson) : [];
            },

            getHiddenCols() {
                const hiddenColsJson = window.sessionStorage.getItem(this.hiddenColsStorageName);
                return hiddenColsJson ? JSON.parse(hiddenColsJson) : this.hiddenCols;
            },

            toggleColumn(key) {
                const index = this.hiddenCols.indexOf(key);
                if (index !== -1) {
                    this.hiddenCols.splice(index, 1);
                } else {
                    this.hiddenCols.push(key);
                }
                this.storeHiddenColumns();
            },

            isColumnVisible(key) {
                return !this.hiddenCols.includes(key);
            },

            storeHiddenColumns() {
                this.storeValues(this.hiddenColsStorageName, this.hiddenCols);
            },

            storeSelectedRows() {
                this.storeValues(this.massActionStorageName, this.selectedRows);
            },

            storeValues(key, values) {
                window.sessionStorage.setItem(key, JSON.stringify(values.filter(value => null !== value)));
            },

            selectAllCheckbox($event) {
                const checked = !!$event.target.checked;
                document.querySelectorAll('.rowCheckbox').forEach(checkbox => {
                    const index = this.selectedRows.indexOf(checkbox.value);
                    if (checked && index === -1) {
                        this.selectedRows.push(checkbox.value);
                    } else if (!checked && index > -1) {
                        this.selectedRows.splice(index, 1);
                    }
                });
            },
            doMassAction(option) {
                const url = option.value;
                const form = this.refs['massaction-form'];
                const checked = this.getSelectedRows();
                const select = this.refs['massaction-select'];

                if (!url || !form || !select) {
                    return;
                }

                if (checked.length === 0) {
                    alert('<?= __("Please select the records to apply the mass action to.")?>');
                    select.selectedIndex = 0;
                    return;
                }
                if (option.dataset.requireConfirm === 'true' && !confirm('<?= __("Are you sure?")?>')) {
                    select.selectedIndex = 0;
                    return;
                }
                const rowCheckboxName = '<?= $escaper->escapeHtml($grid->getMassActionIdsParam()) ?>[]';

                const alreadyPresent = Array.from(form.elements)
                    .filter(element => element.name === rowCheckboxName)
                    .filter(element => element.checked)
                    .map(element => element.value);

                const missing = checked.filter(value => !alreadyPresent.includes(value));

                missing.forEach(value => {
                    const input = document.createElement('input');
                    input.type = 'hidden';
                    input.name = rowCheckboxName;
                    input.value = value;
                    form.append(input);
                });

                form.action = url;

                this.resetFormState();

                this.loading = true;
                form.submit();
            },

            resetFormState() {
                this.selectedRows = [];

                if (this.refs && this.refs['select-all']) {
                    this.refs['select-all'].checked = false;
                }

                if (this.refs && this.refs['massaction-select']) {
                    this.refs['massaction-select'].value = 0;
                }
            },

            formGridUpdate(form) {
                this.filterUri = this.getFormUriEncoded(form);
                this.updateGrid(this.filterUri);
            },

            getFormUriEncoded(form) {
                const url = new URL(form.action);
                Array.from(form.elements).forEach(
                    input => url.searchParams.set(input.name, input.value)
                );
                return url.toString();
            },

            updateGrid(url) {
                if (<?= (int) $navigation->isAjaxEnabled() ?>) {
                    this.ajaxGridUpdate(url);
                } else {
                    window.location.href = url;
                }
            },

            ajaxGridUpdate(url) {
                this.loading = true;
                fetch(url, {
                    method: 'get',
                    headers: {'Content-Type': 'application/json'}
                })
                    .then(response => response.json())
                    .then(responseBody => {
                        this.loading = false;
                        if (responseBody.message) alert(responseBody.message);
                        if (responseBody.grid_html) {
                            const tmpContainer = document.createElement('div');
                            tmpContainer.innerHTML = responseBody.grid_html;
                            this.$el.replaceWith(tmpContainer.querySelector('.hyva-admin-grid'));
                        }
                    })
                    .catch(console.error);
            },

            dispatchRowEvent(event, name, params) {
                const row = closest('TR', event.target, this.$el);
                const eventData = {origEvent: event, row: row, viewModel: this};
                window.dispatchEvent(new CustomEvent(name, {detail: Object.assign(params || {}, eventData)}));
            }
        }
    }
</script>
