<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Hyva\Admin\ViewModel\HyvaForm\FormFieldDefinitionInterface $field */

?>
<div class="">
    <label for="<?= $escaper->escapeHtmlAttr($field->getName()) ?>">
        <?= $escaper->escapeHtml($field->getLabel()) ?>:
        <!--<br/>This is some super long text content because I want to see how the cell really resizes to accommodate, omg it still just keeps on going and going honk honk wtf omg when will I reach the end of the line though?-->
    </label>
</div>
<div class="">
    <?= $field->getContentHtml() ?>
    <!--<br/>This is some super long text content because I want to see how the cell really resizes to accommodate, omg it still just keeps on going and going honk honk wtf omg when will I reach the end of the line though?-->
</div>
