<?php declare(strict_types=1);

/** @var \Hyva\Admin\Block\Adminhtml\HyvaForm $block */
/** @var \Magento\Framework\Escaper $escaper */

$escaper = $escaper ?? $block;

$form       = $block->getForm();
$uniqueId   = '_' . md5($form->getFormName());
$navigation = $form->getNavigation();
$buttons    = $navigation->getButtons();
?>
<script>
    function init_form_<?= $uniqueId ?>() {
        return {
            activeSection: '<?= $form->getDefaultActiveSectionId() ?>',
            activeGroups: <?= json_encode($form->getDefaultActiveGroupsMap()) ?>,
            isActiveGroup: function(section, group) {
                return this.activeGroups[section] === group;
            }
        }
    }
</script>
<!-- Hyva_Admin form "<?= $escaper->escapeHtml($form->getFormName()) ?>" -->
<form x-data="init_form_<?= $uniqueId ?>()">
    <div class="hyva-admin-form">
        <div class="max-w-full px-0 py-6 mx-auto">

            <div>
                <?php foreach ($navigation->getButtons() as $button): ?>
                    <?= $button->getHtml() ?>
                <?php endforeach; ?>
            </div>

            <div class="flex flex-col md:flex-row">
                <?php if ($form->hasDeclaredSections()): ?>
                    <div class="w-screen max-w-sm mr-10">
                        <?php foreach ($form->getSections() as $section): ?>
                            <div class="border border-gray-400 -mb-px py-2 px-10 text-center cursor-pointer"
                                @click="activeSection = '<?= $section->getId() ?>'"
                                 x-bind:class="{ 'font-bold': activeSection === '<?= $section->getId() ?>' }">
                                <?= $escaper->escapeHtml($section->getLabel()) ?>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>

                <div class="flex-grow">
                    <?php foreach ($form->getSections() as $section): ?>
                        <div class="section-<?= $section->getId() ?>"
                             x-show="activeSection === '<?= $section->getId()?>'">
                            <?= $section->getHtml() ?>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</form>
