<?php declare(strict_types=1);

/** @var \Hyva\Admin\Block\Adminhtml\HyvaForm $block */
/** @var \Magento\Framework\Escaper $escaper */

$escaper = $escaper ?? $block;

$form       = $block->getForm();
$uniqueId   = '_' . md5($form->getFormName());
$navigation = $form->getNavigation();
$buttons    = $navigation->getButtons();
?>
<!-- Hyva_Admin form "<?= $escaper->escapeHtml($form->getFormName()) ?>" -->
<div class="hyva-admin-form">
    <div class="max-w-full px-0 py-6 mx-auto">

        <div>
            <?php foreach ($navigation->getButtons() as $button): ?>
                <?= $button->getHtml() ?>
            <?php endforeach; ?>
        </div>

        <div class="flex flex-col md:flex-row">
            <?php if (!$form->hasOnlyDefaultSection() && !empty($form->getSections())): ?>
                <div class="w-screen max-w-sm mr-10 flex flex-col">
                    <!-- One day this is supposed to render as tabs to click on -->
                    <?php foreach ($form->getSections() as $section): ?>
                        <div class="border border-gray-400 -mb-px py-2 px-10 text-center cursor-pointer">
                            <?= $escaper->escapeHtml($section->getLabel()) ?>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <div>
                <?php foreach ($form->getSections() as $section): ?>
                    <div class="section-<?= $section->getId() ?>">
                        <?= $section->getHtml() ?>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>
