<?php declare(strict_types=1);

/** @var \Hyva\Admin\Block\Adminhtml\HyvaGrid $block */
/** @var \Magento\Framework\Escaper $escaper */

$grid       = $block->getGrid();
$navigation = $grid->getNavigation();
$uniqueId = '_' . uniqid();
?>
<div class="hyva-admin-grid"
     x-data="initDataTable<?= /** @noEscape */ $uniqueId ?>()"
     x-init="getSelectedRows(); $watch('selectedRows', selectedRows => storeSelectedRows(selectedRows));">
    <div class="max-w-full px-0 py-6 mx-auto">
        <div class="flex items-center justify-between mb-4">
            <div class="flex-1 pr-4">
                <div class="relative flex flex-wrap md:w-3/4 gap-x-8">
                    <div class="self-center">
                        <span class="font-medium text-md">
                            <?= $escaper->escapeHtml(__('Current Page:')) ?>
                        </span>
                        <?= (int) $navigation->getCurrentPageNumber() ?>
                    </div>

                    <div class="self-center">
                        <span class="font-medium text-md">
                            <?= $escaper->escapeHtml(__('Total Pages:')) ?>
                        </span>
                        <?= (int) $navigation->getPageCount() ?>
                    </div>

                    <div>
                        <label for="pageSize">
                            <?= $escaper->escapeHtml(__('Rows Per Page:')) ?>
                        </label>
                        <script>
                            function goToOptionUrl(option) {
                                const url = option.value;
                                if (url) {
                                    window.location.href=url;
                                }
                            }
                        </script>
                        <select id="pageSize" onchange="goToOptionUrl(this.selectedOptions[0])"
                                class="form-select">
                            <?php foreach ($navigation->getPageSizes() as $pageSize): ?>
                                <?php $currentPageSize = $navigation->getPageSize() === $pageSize ?>
                            <option value="<?= $escaper->escapeUrl($navigation->getUrlForPageSize($pageSize)) ?>"
                                <?= $currentPageSize ? 'selected' : '' ?>>
                                <?= (int) $pageSize ?>
                            </option>
                            <?php endforeach; ?>
                        </select>
                    </div>

                    <div class="relative z-0 inline-flex rounded-md shadow-sm">
                        <?php if ($navigation->hasPreviousPage()): ?>
                            <a href="<?= $escaper->escapeUrl($navigation->getPreviousPageUrl()) ?>"
                            class="relative inline-flex items-center px-4 py-2 font-medium text-gray-700 bg-white
                                border border-gray-300 rounded-l-md hover:bg-gray-50 focus:z-10 focus:outline-none
                                focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
                            >
                                <?= $escaper->escapeHtml(__('Previous Page')) ?>
                            </a>
                        <?php else: ?>
                            <span class="relative inline-flex items-center px-4 py-2 font-medium text-gray-300 bg-white
                                border border-gray-300 cursor-not-allowed rounded-l-md">
                                <?= $escaper->escapeHtml(__('Previous Page')) ?>
                            </span>
                        <?php endif; ?>
                        <?php if ($navigation->hasNextPage()): ?>
                            <a href="<?= $escaper->escapeUrl($navigation->getNextPageUrl()) ?>"
                            class="relative inline-flex items-center px-4 py-2 -ml-px font-medium text-gray-700 bg-white
                                border border-gray-300 rounded-r-md hover:bg-gray-50 focus:z-10 focus:outline-none
                                focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
                            >
                                <?= $escaper->escapeHtml(__('Next Page')) ?>
                            </a>
                        <?php else: ?>
                            <span class="relative inline-flex items-center px-4 py-2 -ml-px font-medium text-gray-300
                            bg-white border border-gray-300 cursor-not-allowed rounded-r-md"
                            >
                                <?= $escaper->escapeHtml(__('Next Page')) ?>
                            </span>
                        <?php endif; ?>
                    </div>

                    <?php if ($navigation->hasAppliedFilters()): ?>
                    <div>
                        <a href="<?= $escaper->escapeUrl($navigation->getResetFiltersUrl()) ?>"
                           class="btn btn-primary">
                            <?= $escaper->escapeHtml(__('Reset filters')) ?>
                        </a>
                    </div>
                    <?php endif; ?>
                </div>
            </div>
            <div>
                <div class="flex">
                    <div class="relative">
                        <button @click.prevent="open = !open"
                                class="inline-flex items-center px-2 py-2 font-semibold text-gray-500 bg-white
                                    rounded-lg hover:text-blue-500 focus:outline-none focus:shadow-outline md:px-4"
                        >
                            <svg xmlns="http://www.w3.org/2000/svg"
                                 class="w-6 h-6 md:hidden md:visible"
                                 viewBox="0 0 24 24"
                                 stroke-width="2"
                                 stroke="currentColor"
                                 fill="none"
                                 stroke-linecap="round"
                                 stroke-linejoin="round"
                            >
                                <rect x="0" y="0" width="24" height="24" stroke="none"></rect>
                                <path
                                    d="M5.5 5h13a1 1 0 0 1 0.5 1.5L14 12L14 19L10 16L10 12L5 6.5a1 1 0 0 1 0.5 -1.5" />
                            </svg>
                            <span class="hidden md:block md:visible">
                                <?= $escaper->escapeHtml(__('Display')) ?>
                            </span>
                            <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 ml-1" width="24" height="24"
                                 viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                                 stroke-linecap="round" stroke-linejoin="round">
                                <rect x="0" y="0" width="24" height="24" stroke="none"></rect>
                                <polyline points="6 9 12 15 18 9" />
                            </svg>
                        </button>

                        <div x-show="open"
                             @click.away="open = false"
                             class="absolute top-0 right-0 z-40 block p-4 mt-16 -mr-1 overflow-y-auto bg-white
                                rounded-lg shadow-lg"
                             style="max-height: 75vh;">
                            <template x-for="heading in headings">
                                <label
                                    class="flex items-center justify-start px-4 py-2 text-truncate hover:bg-gray-100">
                                    <div class="mr-3 text-teal-600">
                                        <input type="checkbox"
                                               class="form-checkbox focus:outline-none focus:shadow-outline"
                                               checked
                                               @click="toggleColumn(heading.key)"
                                        >
                                    </div>
                                    <div class="text-gray-700 select-none"
                                         x-text="heading.value">
                                    </div>
                                </label>
                            </template>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <?php if ($massActions = $grid->getMassActions()): ?>
                <?php $massActionFormId = 'hyva-grid-massaction-' . $grid->getGridName() ?>
            <form id="<?= $escaper->escapeHtmlAttr($massActionFormId) ?>" method="post">
                <?= $block->getBlockHtml('formkey'); ?>
                <label for="massAction<?= /** @noEscape */ $uniqueId ?>" class="mr-8">
                    <?= $escaper->escapeHtml(__('Mass Actions:')) ?>
                </label>
                <select @change="doMassAction($event.target.selectedOptions[0])"
                        @keydown.enter="doMassAction($event.target.selectedOptions[0])"
                        id="massAction<?= /** @noEscape */ $uniqueId ?>"
                        name="massAction"
                        class="form-select"
                        form="<?= $escaper->escapeHtmlAttr($massActionFormId) ?>">
                    <option disabled selected hidden>
                        <?= $escaper->escapeHtml(__('Select an action')) ?>
                    </option>
                    <?php foreach ($massActions as $massAction): ?>
                        <?php $massActionUrl = $block->getUrl($massAction->getUrl()) ?>
                        <option data-require-confirm="<?= $massAction->requireConfirmation() ? 'true' : 'false' ?>"
                                value="<?= $escaper->escapeUrl($massActionUrl) ?>">
                            <?= $escaper->escapeHtml($massAction->getLabel()) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
                <?php if ($massActions) { ?></form><?php } ?>
                <?php endif; ?>
            <div x-show="selectedRows.length > 0" class="mt-4">
                <span>
                    <?= $escaper->escapeHtml(__('Total selected:')) ?>
                </span> <span x-text="selectedRows.length" >
                </span>
                <a href="#" @click.prevent="selectedRows=[]" class="ml-4 underline">
                    <?= $escaper->escapeHtml(__('reset selection')) ?></a>
            </div>
            <?php if ($navigation->hasFilters()): ?>
            <form id="<?= $escaper->escapeHtmlAttr($navigation->getFilterFormId()) ?>"
                  method="get"
                  action="<?= $escaper->escapeUrl($navigation->getFilterFormUrl()) ?>">
                <input type="submit" hidden />
            </form>
            <?php endif; ?>
        </div>
    </div>

    <div class="flex flex-col table-container">
        <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
                <div class="overflow-hidden border-b border-gray-200">
                    <table class="min-w-full divide-y divide-gray-200">
                        <thead>
                        <tr class="text-left table-head">
                            <?php if ($massActions): ?>
                                <th class="select-all">
                                    <label
                                        class="inline-flex items-center justify-between px-2 py-2 rounded-lg
                                            cursor-pointer hover:bg-gray-200">
                                        <input type="checkbox"
                                               class="form-checkbox focus:outline-none focus:shadow-outline"
                                               @click="selectAllCheckbox($event);">
                                    </label>
                                </th>
                            <?php endif; ?>
                            <?php foreach ($grid->getColumnDefinitions() as $column): ?>
                                <?php $isSortedByColumn = $column->isSortable() &&
                                    $navigation->getSortByColumn() === $column->getKey() ?>
                                <?php $newDirection = $isSortedByColumn &&
                                    $navigation->isSortOrderAscending() ? 'desc' : 'asc' ?>
                                <th class="relative pr-12 col-<?= $escaper->escapeHtml($column->getKey()) ?>
                                        <?php if ($column->isSortable()): ?> sortable<?php endif; ?>"
                                    x-ref="col-<?= $escaper->escapeHtmlAttr($column->getKey()) ?>"
                                    <?php if ($column->isSortable()): ?>
                                        onclick="window.location.href =
                                            '<?= $escaper
                                                ->escapeUrl(
                                                    $navigation->getSortByUrl($column->getKey(), $newDirection)
                                                ) ?>'"
                                    <?php endif; ?>>
                                    <?= $escaper->escapeHtml($column->getLabel()) ?>
                                    <?php if ($isSortedByColumn && $navigation->isSortOrderAscending()): ?>
                                    <span class="absolute right-0 w-6 my-1 mr-2 align-middle text-primary">
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none"
                                             viewBox="0 0 24 24" stroke="currentColor"
                                        >
                                            <path stroke-linecap="round"
                                                  stroke-linejoin="round"
                                                  stroke-width="2"
                                                  d="M3 4h13M3 8h9m-9 4h6m4 0l4-4m0 0l4 4m-4-4v12"
                                            />
                                        </svg>
                                    </span>
                                    <?php endif; ?>
                                    <?php if ($isSortedByColumn && !$navigation->isSortOrderAscending()): ?>
                                        <span class="absolute right-0 w-6 w-8 h-6 h-8 mr-2 align-middle text-primary">
                                            <svg xmlns="http://www.w3.org/2000/svg"
                                                 fill="none"
                                                 viewBox="0 0 24 24"
                                                 stroke="currentColor"
                                            >
                                                <path stroke-linecap="round"
                                                      stroke-linejoin="round"
                                                      stroke-width="2"
                                                      d="M3 4h13M3 8h9m-9 4h9m5-4v12m0 0l-4-4m4 4l4-4"
                                                />
                                            </svg>
                                        </span>
                                    <?php endif; ?>
                                </th>
                            <?php endforeach; ?>
                            <?php if ($actions = $grid->getActions()): ?>
                                <th class="sticky top-0 table-cell px-6 py-2 text-xl font-semibold tracking-wider
                                    text-gray-300 uppercase align-middle border border-gray-200 actions
                                    bg-container-darker"
                                >
                                    <?= $escaper->escapeHtml(__('Actions')) ?>
                                </th>
                            <?php endif; ?>
                        </tr>
                        <?php if ($navigation->hasFilters()): ?>
                        <tr class="table-filters">
                            <?php if ($massActions): ?>
                                <th class="sticky top-0 px-3 py-2 border border-gray-200"></th>
                            <?php endif; ?>
                            <?php foreach ($grid->getColumnDefinitions() as $column): ?>
                            <th class="col-<?= $escaper->escapeHtml($column->getKey()) ?> sticky top-0 border
                                border-gray-200 px-6 py-2 text-gray-600 tracking-wider text-xl table-cell align-left"
                            >
                                <?php $filter = $navigation->getFilter($column->getKey()) ?>
                                <?= $filter ? $filter->getHtml() : '' ?>
                            </th>
                            <?php endforeach; ?>
                            <?php if ($actions): ?>
                                <th class="sticky top-0 px-3 py-2 border border-gray-200"></th>
                            <?php endif; ?>
                        </tr>
                        <?php endif; ?>
                        </thead>
                        <tbody>
                        <?php foreach ($grid->getRows() as $row): ?>
                            <?php if ($rowAction = $actions[$grid->getRowActionId()] ?? false) {
                                $rowActionUrl       = $block->getUrl($rowAction->getUrl(), $rowAction->getParams($row));
                                $rowActionAttribute = sprintf(
                                    "onclick=\"window.location.href='%s'\"",
                                    $escaper->escapeJs($rowActionUrl)
                                );
                            } else {
                                $rowActionAttribute = '';
                            } ?>
                            <tr class="table-content">
                                <?php if ($massActions): ?>
                                    <td class="px-3 border border-gray-100">
                                        <label
                                            class="inline-flex items-center justify-between px-2 py-2 text-teal-500
                                            rounded-lg cursor-pointer hover:bg-gray-200">
                                        <input form="<?= $escaper->escapeHtmlAttr($massActionFormId) ?>"
                                               type="checkbox"
                                               value="<?= $escaper
                                                           ->escapeHtmlAttr(
                                                               $row
                                                                   ->getCell($grid->getMassActionIdColumn())
                                                                   ->getRawValue()
                                                           ) ?>"
                                               name="<?= $escaper->escapeHtmlAttr($grid->getMassActionIdsParam()) ?>[]"
                                               class="form-checkbox rowCheckbox focus:outline-none focus:shadow-outline"
                                               x-model="selectedRows"

                                        />
                                    </td>
                                <?php endif; ?>
                                <?php foreach ($row->getCells() as $cell): ?>
                                    <td class="col-<?= $escaper
                                        ->escapeHtmlAttr($cell->getColumnDefinition()->getKey()); ?>"
                                        <?= $escaper->escapeHtml($rowActionAttribute) ?>>
                                        <?= $cell->getHtml() ?>
                                    </td>
                                <?php endforeach; ?>
                                <?php if ($actions): ?>
                                    <td class="px-3 text-right border border-gray-100 actions">
                                        <?php foreach ($actions as $action): ?>
                                            <a class="px-3 font-medium text-blue-800 whitespace-no-wrap
                                                hover:text-blue-600"
                                               href="<?= $escaper
                                                   ->escapeUrl($block->getUrl(
                                                       $action->getUrl(),
                                                       $action->getParams($row)
                                                   )) ?>">
                                                <?= $escaper->escapeHtml($action->getLabel()) ?>
                                            </a>
                                        <?php endforeach; ?>
                                    </td>
                                <?php endif; ?>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
    <script>
        function initDataTable<?= /** @noEscape */ $uniqueId ?>() {

            return {
                selectedRows: [],
                massActionStorageName: '<?= $escaper->escapeHtml($grid->getGridName()) . '-selectedRows' ?>',

                getSelectedRows() {
                    const massActionStorageName = this.massActionStorageName;
                    const selectedRowsJson = window.sessionStorage.getItem(
                        massActionStorageName
                    );
                    this.selectedRows = selectedRowsJson ? JSON.parse(selectedRowsJson) : [];

                    return this.selectedRows;
                },

                headings: [
                    <?php foreach ($grid->getColumnDefinitions() as $column): ?>
                    {
                        'key': 'col-<?= $escaper->escapeHtml($column->getKey()) ?>',
                        'value': '<?= $escaper->escapeHtml($column->getLabel()) ?>'
                    },
                    <?php endforeach; ?>
                ],

                open: false,

                toggleColumn(key) {
                    let columns = document.querySelectorAll('.' + key);

                    if (this.$refs[key].classList.contains('hidden') &&
                        this.$refs[key].classList.contains(key)
                    ) {
                        columns.forEach(column => {
                            column.classList.remove('hidden');
                        });
                    } else {
                        columns.forEach(column => {
                            column.classList.add('hidden');
                        });
                    }
                },

                selectAllCheckbox($event) {
                    const checked = !!$event.target.checked;
                    document.querySelectorAll('.rowCheckbox').forEach(checkbox => {
                        const index = this.selectedRows.indexOf(checkbox.value);
                        if (checked && index === -1) {
                            this.selectedRows.push(checkbox.value);
                        } else if (! checked && index > -1) {
                            this.selectedRows.splice(index, 1);
                        }
                    });
                },

                doMassAction(option) {
                    const url = option.value;
                    const form = document.getElementById('<?= $escaper->escapeHtml($massActionFormId) ?>');
                    const checked = this.getSelectedRows();
                    const select = form.querySelectorAll('select[name="massAction"]')[0];
                    if (! url) {
                        return;
                    }
                    if (checked.length === 0) {
                        alert('Please select the records to apply the mass action to.');
                        select.selectedIndex = 0;
                        return;
                    }
                    if (option.dataset.requireConfirm === 'true' && ! confirm('Are you sure?')) {
                        select.selectedIndex = 0;
                        return;
                    }
                    const alreadyPresent = [...form.elements].filter(e => e.checked).map(e => e.value);
                    const missing = checked.filter(v => ! alreadyPresent.includes(v));
                    const newFields = missing.map(v => {
                        const input = document.createElement('input');
                        input.type = 'hidden';
                        input.name = '<?= $escaper->escapeHtml($grid->getMassActionIdsParam()) ?>[]';
                        input.value = v;
                        return input;
                    });
                    newFields.length > 0 && form.append(...newFields);
                    form.action = url;
                    this.selectedRows = [];
                    form.submit();
                },

                storeSelectedRows(selectedRows) {
                    const values = selectedRows.filter(value => null !== value);
                    window.sessionStorage.setItem(
                        this.massActionStorageName,
                        JSON.stringify(values)
                    );
                }

            }
        }
    </script>
<div class="container px-4 py-6 mx-auto">
    <?php if (!$grid->getRows()) { ?>
        <div>
            <?= $escaper->escapeHtml(
                __('No %1 found.', $grid->getEntityDefinition()->getLabelPlural())
            ) ?>
        </div>
    <?php } ?>
</div>
