<?php declare(strict_types=1);

// This template exists for testing purposes.
// Removing it will break tests.

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Hyva\Admin\ViewModel\HyvaGrid\GridFilterInterface $filter */

?>
Filter for column <?= $filter->getColumnDefinition()->getKey() ?> with input type <?= $filter->getInputType() ?>.
