<?php declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */

$escaper = $escaper ?? $block;

?>
<div class="actions inline-flex mx-2">
    <button @click.prevent="open = !open"
            class="inline-flex items-center px-2 py-2 font-semibold text-gray-500 bg-white
                   rounded-lg hover:text-blue-500 focus:outline-none focus:shadow-outline md:px-4"
    >
        <svg xmlns="http://www.w3.org/2000/svg"
             class="w-6 h-6 md:hidden"
             viewBox="0 0 24 24"
             stroke-width="2"
             stroke="currentColor"
             fill="none"
             stroke-linecap="round"
             stroke-linejoin="round"
        >
            <rect x="0" y="0" width="24" height="24" stroke="none"></rect>
            <path d="M5.5 5h13a1 1 0 0 1 0.5 1.5L14 12L14 19L10 16L10 12L5 6.5a1 1 0 0 1 0.5 -1.5"/>
        </svg><!-- filter -->
        <span class="hidden md:block md:visible">
            <?= $escaper->escapeHtml(__('Display')) ?>
        </span>
        <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 ml-1" width="24" height="24"
             viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
             stroke-linecap="round" stroke-linejoin="round">
            <rect x="0" y="0" width="24" height="24" stroke="none"></rect>
            <polyline points="6 9 12 15 18 9"/><!-- filter down icon -->
        </svg><!-- chevron-down -->
    </button>

    <div x-show="open"
         @click.away="open = false"
         class="absolute top-0 right-0 z-40 block p-4 mt-16 -mr-1 overflow-y-auto bg-white
                            rounded-lg shadow-lg"
         style="max-height: 75vh;">
        <template x-for="column in columns">
            <label
                class="flex items-center justify-start px-4 py-2 text-truncate hover:bg-gray-100">
                <div class="mr-3 text-teal-600">
                    <input type="checkbox"
                           class="form-checkbox focus:outline-none focus:shadow-outline"
                           :checked="isColumnVisible(column.key)"
                           @click="toggleColumn(column.key)"
                    >
                </div>
                <div class="text-gray-700 select-none"
                     x-text="column.value">
                </div>
            </label>
        </template>
    </div>
</div>
