<?php declare(strict_types=1);

/** @var \Magento\Framework\Escaper $escaper */
/** @var \Hyva\Admin\ViewModel\HyvaGrid\GridExportInterface[] $exports */
/** @var \Hyva\Admin\ViewModel\HyvaGrid\NavigationInterface $navigation  */

$escaper = $escaper ?? $block;

if ($exports): ?>
    <div class="exports inline-flex mx-2">
        <button @click.prevent="openExport = !openExport"
                class="inline-flex items-center px-2 py-2 font-semibold text-gray-500 bg-white
                                    rounded-lg hover:text-blue-500 focus:outline-none focus:shadow-outline md:px-4"
        >
            <svg xmlns="http://www.w3.org/2000/svg"
                 class="w-6 h-6 md:hidden"
                 viewBox="0 0 24 24"
                 stroke-width="2"
                 stroke="currentColor"
                 fill="none"
                 stroke-linecap="round"
                 stroke-linejoin="round"
            >
                <rect x="0" y="0" width="24" height="24" stroke="none"></rect>
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M9 19l3 3m0 0l3-3m-3 3V10" />
            </svg><!-- cloud-download -->
            <span class="hidden md:block md:visible">
                <?= $escaper->escapeHtml(__('Export')) ?>
            </span>
            <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 ml-1" width="24" height="24"
                 viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                 stroke-linecap="round" stroke-linejoin="round">
                <rect x="0" y="0" width="24" height="24" stroke="none"></rect>
                <polyline points="6 9 12 15 18 9"/>
            </svg><!-- chevron down -->
        </button>

        <div x-show="openExport"
             @click.away="openExport = false"
             class="absolute top-0 z-40 block p-4 mt-16 -mr-1 overflow-y-auto bg-white
                    rounded-lg shadow-lg flex flex-col"
             style="max-height: 75vh;">
            <?php foreach ($exports as $export): ?>
                <a href="<?= $escaper->escapeHtmlAttr($navigation->getExportUrl($export->getType())) ?>"
                   @click="openExport = false"
                   class="text-gray-700 inline-flex mx-2 cursor-pointer my-2">
                    <span><?= $escaper->escapeHtml($export->getLabel()) ?></span>
                </a>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
