<?php declare(strict_types=1);

/** @var \Magento\Framework\Escaper $escaper */
/** @var \Hyva\Admin\ViewModel\HyvaGrid\NavigationInterface $navigation */

$escaper = $escaper ?? $block;

?>
<?php if ($navigation->isPagerEnabled()): ?>
    <div class="self-center">
                        <span class="font-medium text-md mr-4">
                            <?= $escaper->escapeHtml(__('Current Page:')) ?>
                        </span>
        <?= (int) $navigation->getCurrentPageNumber() ?>
    </div>

    <div class="self-center">
                        <span class="font-medium text-md mr-4">
                            <?= $escaper->escapeHtml(__('Total Pages:')) ?>
                        </span>
        <?= (int) $navigation->getPageCount() ?>
    </div>

    <div>
        <label for="pageSize" class="font-medium text-md mr-4">
            <?= $escaper->escapeHtml(__('Rows Per Page:')) ?>
        </label>
        <select id="pageSize" @change="updateGrid($event.target.selectedOptions[0].value)"
                class="form-select">
            <?php foreach ($navigation->getPageSizes() as $pageSize): ?>
                <?php $currentPageSize = $navigation->getPageSize() === $pageSize ?>
                <option value="<?= $escaper->escapeUrl($navigation->getUrlForPageSize($pageSize)) ?>"
                    <?= $currentPageSize ? 'selected' : '' ?>>
                    <?= (int) $pageSize ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>

    <div class="relative z-0 inline-flex rounded-md shadow-sm">
        <?php if ($navigation->hasPreviousPage()): ?>
            <a href="<?= $escaper->escapeUrl($navigation->getFirstPageUrl()) ?>"
               @click.prevent="updateGrid($event.target.href)"
               class="relative inline-flex items-center px-4 py-2 font-medium text-gray-700 bg-white
                                border border-gray-300 rounded-l-md hover:bg-gray-50 focus:z-10 focus:outline-none
                                focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            >
                <?= $escaper->escapeHtml(__('First Page')) ?>
            </a>
            <a href="<?= $escaper->escapeUrl($navigation->getPreviousPageUrl()) ?>"
               @click.prevent="updateGrid($event.target.href)"
               class="relative inline-flex items-center px-4 py-2 -ml-px font-medium text-gray-700 bg-white
                                border border-gray-300 hover:bg-gray-50 focus:z-10 focus:outline-none
                                focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            >
                <?= $escaper->escapeHtml(__('Previous Page')) ?>
            </a>
        <?php else: ?>
            <span class="relative inline-flex items-center px-4 py-2 font-medium text-gray-300 bg-white
                                border border-gray-300 cursor-not-allowed rounded-l-md">
                                <?= $escaper->escapeHtml(__('First Page')) ?>
                            </span>
            <span class="relative inline-flex items-center px-4 py-2 -ml-px font-medium text-gray-300
                                bg-white border border-gray-300 cursor-not-allowed">
                                <?= $escaper->escapeHtml(__('Previous Page')) ?>
                            </span>
        <?php endif; ?>
        <?php if ($navigation->hasNextPage()): ?>
            <a href="<?= $escaper->escapeUrl($navigation->getNextPageUrl()) ?>"
               @click.prevent="updateGrid($event.target.href)"
               class="relative inline-flex items-center px-4 py-2 -ml-px font-medium text-gray-700 bg-white
                                border border-gray-300 rounded-r-md hover:bg-gray-50 focus:z-10 focus:outline-none
                                focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            >
                <?= $escaper->escapeHtml(__('Next Page')) ?>
            </a>
            <a href="<?= $escaper->escapeUrl($navigation->getLastPageUrl()) ?>"
               @click.prevent="updateGrid($event.target.href)"
               class="relative inline-flex items-center px-4 py-2 -ml-px font-medium text-gray-700 bg-white
                                border border-gray-300 rounded-r-md hover:bg-gray-50 focus:z-10 focus:outline-none
                                focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            >
                <?= $escaper->escapeHtml(__('Last Page')) ?>
            </a>
        <?php else: ?>
            <span class="relative inline-flex items-center px-4 py-2 -ml-px font-medium text-gray-300
                            bg-white border border-gray-300 cursor-not-allowed"
            >
                                <?= $escaper->escapeHtml(__('Next Page')) ?>
                            </span>
            <span class="relative inline-flex items-center px-4 py-2 -ml-px font-medium text-gray-300
                            bg-white border border-gray-300 cursor-not-allowed rounded-r-md"
            >
                                <?= $escaper->escapeHtml(__('Last Page')) ?>
                            </span>
        <?php endif; ?>
    </div>
<?php endif; ?>

<?php if ($navigation->hasAppliedFilters()): ?>
    <div>
        <a href="<?= $escaper->escapeUrl($navigation->getResetFiltersUrl()) ?>"
           @click.prevent="updateGrid($event.target.href)"
           class="btn btn-primary">
            <?= $escaper->escapeHtml(__('Reset filters')) ?>
        </a>
    </div>
<?php endif; ?>
